"""initial migration

Revision ID: 52477364c991
Revises: 
Create Date: 2026-01-27 10:58:57.452794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52477364c991'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditorios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('ubicacion', sa.String(length=200), nullable=True),
    sa.Column('capacidad', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditorios_nombre'), 'auditorios', ['nombre'], unique=True)
    op.create_table('dependencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('sigla', sa.String(length=20), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eventos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(), nullable=False),
    sa.Column('jornada', sa.String(length=20), nullable=False),
    sa.Column('aforo_estimado', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('requiere_microfono', sa.Boolean(), nullable=False),
    sa.Column('requiere_videobeam', sa.Boolean(), nullable=False),
    sa.Column('requiere_sonido', sa.Boolean(), nullable=False),
    sa.Column('requiere_asistencia_tecnica', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('auditorio_id', sa.Integer(), nullable=False),
    sa.Column('dependencia_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['auditorio_id'], ['auditorios.id'], ),
    sa.ForeignKeyConstraint(['dependencia_id'], ['dependencias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eventos')
    op.drop_table('dependencias')
    op.drop_index(op.f('ix_auditorios_nombre'), table_name='auditorios')
    op.drop_table('auditorios')
    # ### end Alembic commands ###
