"""Restore historial_eventos

Revision ID: a11563d26567
Revises: ccad0c0de498
Create Date: 2026-03-10 15:34:12.158919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a11563d26567'
down_revision: Union[str, Sequence[str], None] = 'ccad0c0de498'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historial_eventos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.Column('accion', sa.String(length=50), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.Column('motivo', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historial_eventos_id'), 'historial_eventos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_historial_eventos_id'), table_name='historial_eventos')
    op.drop_table('historial_eventos')
    # ### end Alembic commands ###
