"""add_contact_fields_to_eventos

Revision ID: ae9d99ba809a
Revises: f48fa62db521
Create Date: 2026-01-27 15:29:07.913649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae9d99ba809a'
down_revision: Union[str, Sequence[str], None] = 'f48fa62db521'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eventos', sa.Column('fecha_solicitud', sa.DateTime(), nullable=False))
    op.add_column('eventos', sa.Column('horario_detalle', sa.String(length=255), nullable=True))
    op.add_column('eventos', sa.Column('responsable_nombre', sa.String(length=150), nullable=False))
    op.add_column('eventos', sa.Column('responsable_telefono', sa.String(length=50), nullable=False))
    op.add_column('eventos', sa.Column('correo_confirmacion', sa.String(length=150), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('eventos', 'correo_confirmacion')
    op.drop_column('eventos', 'responsable_telefono')
    op.drop_column('eventos', 'responsable_nombre')
    op.drop_column('eventos', 'horario_detalle')
    op.drop_column('eventos', 'fecha_solicitud')
    # ### end Alembic commands ###
