"""Add tipo_evento and responsable_cargo

Revision ID: ccad0c0de498
Revises: c2d3e4f5a6b7
Create Date: 2026-03-10 15:31:27.271709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ccad0c0de498'
down_revision: Union[str, Sequence[str], None] = 'c2d3e4f5a6b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historial_eventos')
    op.add_column('eventos', sa.Column('tipo_evento', sa.String(length=100), nullable=True))
    op.add_column('eventos', sa.Column('responsable_cargo', sa.String(length=150), nullable=True))
    op.alter_column('eventos', 'titulo',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('eventos', 'titulo',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.drop_column('eventos', 'responsable_cargo')
    op.drop_column('eventos', 'tipo_evento')
    op.create_table('historial_eventos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('evento_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('accion', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('admin_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fecha', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('observacion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('motivo', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin_users.id'], name=op.f('historial_eventos_admin_id_fkey')),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos.id'], name=op.f('historial_eventos_evento_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('historial_eventos_pkey'))
    )
    # ### end Alembic commands ###
