"""add_bloqueos_auditorio_table

Revision ID: f48fa62db521
Revises: 52477364c991
Create Date: 2026-01-27 14:54:40.474815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f48fa62db521'
down_revision: Union[str, Sequence[str], None] = '52477364c991'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bloqueos_auditorio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auditorio_id', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(), nullable=False),
    sa.Column('motivo', sa.String(length=200), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['auditorio_id'], ['auditorios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bloqueos_auditorio')
    # ### end Alembic commands ###
